openapi: 3.0.3

info:
  title: Top Cryptocurrency Price List API
  description: API that expose an endpoint that returns an up-to-date list of top assets and their current prices in USD when fetched
  termsOfService: http://localhost/terms/
  contact:
    email: santiagoabad@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
externalDocs:
  description: Find out more about Top Cryptocurrency Price List
  url: http://localhost
servers:
  - url: http://localhost:6667
    description: local development server

paths:
  /:
    get:
      tags:
       - Top Crypto List
      summary: Returns Top Crypotocurrency Price List
      description: >
        A list of top cryptocurreny sorted by price. Allows to filter orders
        by date-time and limit the output lenght.
      operationId: getTopCryptoList
      parameters:
      - name: limit
        in: query
        description: Max amount of cryptocurrency types returned
        schema:
          type: integer
          example: "200"
        required: true
      - name: datetime
        in: query
        description: Timestamp of the data to be request. Unix format. Most up to date info if missing
        schema:
          type: datetime
          example: "2022-02-01T12:34:56"
        required: false
      - name: format
        in: query
        description: Indicates the output format, CSV or JSON.        
        required: false
        schema:
          type: string
          format: string
          example: "JSON"
      responses:
        '200':
          description: A list of top cryptocurrencies
          content:
              application/json:
                example:
                  - Rank: 1
                    Symbol: "BTC"
                    Price USD: 45216.1156
                  - Rank: 2
                    Symbol: "ETH"
                    Price USD: 3210.4567
                  - Rank: 3
                    Symbol: "XRP"
                    Price USD: 0.9501
                  - Rank: 4
                    Symbol: "LTC"
                    Price USD: 125.7890
                  - Rank: 5
                    Symbol: "ADA"
                    Price USD: 1.2345
              application/csv:
                example: |
                  Rank,Symbol,Price USD
                  1,BTC,42111.5950546021
                  2,ETH,2268.8872521492
                  3,SOL,95.1784838831
                  4,XRP,0.4931889662
                  5,AVAX,33.0790045024
                  6,ADA,0.4894635802
                  7,BNB,298.9500281192
                  8,SEI,0.6256365317
                  9,MATIC,0.7826507157
                  10,DOGE,0.0785864333
        '404':
          $ref: '#/components/responses/NotFound'
        '422':
          $ref: '#/components/responses/UnprocessableEntity'
        '500':
          $ref: '#/components/responses/InternalServerError'

    
components:
  responses:
    NotFound:
      description: The specified resource was not found.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            detail: "The specified resource was not found."
    UnprocessableEntity:
      description: The payload contains invalid values.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            detail: "The payload contains invalid values."
    InternalServerError:
      description: Internal Server Error.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            detail: "Internal Server Error. Please try again later."


  securitySchemes:
    openId:
      type: openIdConnect
      openIdConnectUrl: https://topcryptolist-dev.eu.auth0.com/.well-known/openid-configuration
    oauth2:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: https://topcryptolist-dev.eu.auth0.com/oauth/token
          scopes: {}
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
    
    api_key:
      type: apiKey
      name: api_key
      in: header

  schemas:
    Error:
      type: object
      properties:
        detail:
          oneOf:
            - type: string
            - type: array
      required:
        - detail
      additionalProperties: false

security:
  - oauth2:
      - getTopCryptoList
  - bearerAuth:
      - getTopCryptoList