# Use an official Python runtime as a parent image
FROM python:3.9-slim

# Set the working directory to /app
WORKDIR /app

# Copy only the necessary files and directories
COPY common/*.py /app/common/
COPY config/*.json /app/config/
COPY shared/*.py /app/shared/
COPY price_service/*.py /app/price_service/
COPY price_service/*.json /app/price_service/
COPY price_service/requirements.txt /app/price_service/


# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r /app/price_service/requirements.txt

# Define environment variable
ENV COINMARKET_API_KEY 'b8d1c1fe-625c-41be-b758-5d39dc8e55c2'

# Run app.py when the container launches
CMD ["python", "-m", "price_service.price_publisher"]